#pragma once

#define LEFT_FRONT_COXA 42
#define LEFT_FRONT_FEMUR 41
#define LEFT_FRONT_TIBIA 40

#define LEFT_MID_COXA 35
#define LEFT_MID_FEMUR 36
#define LEFT_MID_TIBIA 34

#define LEFT_REAR_COXA 4
#define LEFT_REAR_FEMUR 5
#define LEFT_REAR_TIBIA 6

#define RIGHT_FRONT_COXA 43
#define RIGHT_FRONT_FEMUR 44
#define RIGHT_FRONT_TIBIA 45

#define RIGHT_MID_COXA 39
#define RIGHT_MID_FEMUR 38
#define RIGHT_MID_TIBIA 37

#define RIGHT_REAR_COXA 33
#define RIGHT_REAR_FEMUR 32
#define RIGHT_REAR_TIBIA 30
